import 'spec.dart';

/// Turns a [SceneSpec] into copy-paste flutter_scene Dart source that rebuilds
/// the same node tree. The primitive-kind to constructor mapping mirrors the
/// runtime emitter exactly, so the generated code and a live render agree.
///
/// The result is a single function (named [functionName]) returning a small
/// holder with the root [Node] and the framing camera. It assumes the caller's
/// file has these imports:
///
///     import 'dart:math';
///     import 'package:flutter_scene/scene.dart';
///     import 'package:vector_math/vector_math.dart' as vm;
String generateDartSource(SceneSpec spec,
    {String functionName = 'buildScene'}) {
  final out = StringBuffer();

  out.writeln(
      '// Generated by img2scene. Paste into a project that depends on');
  out.writeln('// flutter_scene. Requires these imports:');
  out.writeln('//   import \'dart:math\';');
  out.writeln('//   import \'package:flutter_scene/scene.dart\';');
  out.writeln('//   import \'package:vector_math/vector_math.dart\' as vm;');
  out.writeln();
  out.writeln('/// A built root node and the camera that frames it.');
  out.writeln('class BuiltScene {');
  out.writeln('  BuiltScene(this.root, this.camera);');
  out.writeln('  final Node root;');
  out.writeln('  final PerspectiveCamera camera;');
  out.writeln('}');
  out.writeln();
  out.writeln('BuiltScene $functionName() {');
  out.writeln('  final root = Node(name: \'root\');');
  out.writeln();

  var counter = 0;
  void emit(PartSpec part, String parentVar) {
    final varName = '${_sanitize(part.name)}$counter';
    counter++;

    out.writeln('  final $varName = Node(');
    out.writeln('    name: \'${_escape(part.name)}\',');
    out.writeln('    mesh: Mesh(');
    out.writeln('      ${_geometry(part.primitive)},');
    for (final line in _materialLines(part.material)) {
      out.writeln(line);
    }
    out.writeln('    ),');
    out.write('  )');
    if (part.position != null) {
      out.write('\n    ..position = ${_vec3(part.position!)}');
    }
    if (part.rotation != null) {
      out.write('\n    ..rotation = ${_euler(part.rotation!)}');
    }
    if (part.scale != null) {
      out.write('\n    ..scale = ${_vec3(part.scale!)}');
    }
    out.writeln(';');
    out.writeln('  $parentVar.add($varName);');
    out.writeln();

    for (final child in part.children) {
      emit(child, varName);
    }
  }

  for (final part in spec.parts) {
    emit(part, 'root');
  }

  final cam = spec.camera;
  out.writeln('  final camera = PerspectiveCamera(');
  out.writeln('    position: ${_vec3(cam.position)},');
  out.writeln('    target: ${_vec3(cam.target)},');
  out.writeln('    fovRadiansY: ${_n(cam.fovDegrees)} * pi / 180,');
  out.writeln('  );');
  out.writeln();
  out.writeln('  return BuiltScene(root, camera);');
  out.writeln('}');

  return out.toString();
}

/// Geometry constructor expression for a primitive. Mirrors the runtime
/// emitter's kind mapping one to one.
String _geometry(PrimitiveSpec p) {
  switch (p.kind) {
    case 'cuboid':
      final s = p.param('size', 1);
      return 'CuboidGeometry(vm.Vector3(${_n(p.param('sizeX', s))}, '
          '${_n(p.param('sizeY', s))}, ${_n(p.param('sizeZ', s))}))';
    case 'sphere':
      return 'SphereGeometry(radius: ${_n(p.param('radius', 0.5))})';
    case 'icosphere':
      return 'IcosphereGeometry(radius: ${_n(p.param('radius', 0.5))})';
    case 'cylinder':
      final r = p.param('radius', 0.5);
      return 'CylinderGeometry(bottomRadius: ${_n(p.param('bottomRadius', r))}, '
          'topRadius: ${_n(p.param('topRadius', r))}, '
          'height: ${_n(p.param('height', 1))})';
    case 'cone':
      return 'CylinderGeometry(bottomRadius: ${_n(p.param('radius', 0.5))}, '
          'topRadius: 0.0, height: ${_n(p.param('height', 1))})';
    case 'capsule':
      return 'CapsuleGeometry(radius: ${_n(p.param('radius', 0.5))}, '
          'height: ${_n(p.param('height', 1))})';
    case 'torus':
      return 'TorusGeometry(radius: ${_n(p.param('radius', 0.5))}, '
          'tubeRadius: ${_n(p.param('tubeRadius', 0.2))})';
    case 'plane':
      return 'PlaneGeometry(width: ${_n(p.param('width', 1))}, '
          'depth: ${_n(p.param('depth', 1))})';
    case 'disc':
      return 'DiscGeometry(radius: ${_n(p.param('radius', 0.5))})';
    case 'ring':
      return 'RingGeometry(innerRadius: ${_n(p.param('innerRadius', 0.25))}, '
          'outerRadius: ${_n(p.param('outerRadius', 0.5))})';
    case 'wedge':
      final s = p.param('size', 1);
      return 'WedgeGeometry(vm.Vector3(${_n(p.param('sizeX', s))}, '
          '${_n(p.param('sizeY', s))}, ${_n(p.param('sizeZ', s))}))';
    default:
      return 'CuboidGeometry(vm.Vector3.all(1.0))';
  }
}

/// Material argument lines for the enclosing `Mesh(...)`, indented six spaces.
/// A `PhysicallyBasedMaterial` is always emitted; only the present fields
/// become cascade assignments.
List<String> _materialLines(MaterialSpec? m) {
  final cascades = <String>[];
  if (m != null) {
    if (m.baseColor != null) {
      cascades.add('..baseColorFactor = ${_vec4(m.baseColor!)}');
    }
    if (m.metallic != null) {
      cascades.add('..metallicFactor = ${_n(m.metallic!)}');
    }
    if (m.roughness != null) {
      cascades.add('..roughnessFactor = ${_n(m.roughness!)}');
    }
    if (m.emissive != null) {
      final e = m.emissive!;
      final w = e.length > 3 ? e[3] : 1.0;
      cascades.add('..emissiveFactor = '
          'vm.Vector4(${_n(e[0])}, ${_n(e[1])}, ${_n(e[2])}, ${_n(w)})');
    }
  }
  if (cascades.isEmpty) {
    return ['      PhysicallyBasedMaterial(),'];
  }
  final lines = ['      PhysicallyBasedMaterial()'];
  for (var i = 0; i < cascades.length; i++) {
    final tail = i == cascades.length - 1 ? ',' : '';
    lines.add('        ${cascades[i]}$tail');
  }
  return lines;
}

String _vec3(List<double> v) =>
    'vm.Vector3(${_n(v[0])}, ${_n(v[1])}, ${_n(v[2])})';

String _vec4(List<double> v) => 'vm.Vector4(${_n(v[0])}, ${_n(v[1])}, '
    '${_n(v[2])}, ${_n(v.length > 3 ? v[3] : 1.0)})';

/// Euler degrees `[x, y, z]` to a quaternion, converting to radians and using
/// the emitter's (yaw, pitch, roll) argument order.
String _euler(List<double> d) => 'vm.Quaternion.euler('
    '${_n(d[1])} * pi / 180, '
    '${_n(d[0])} * pi / 180, '
    '${_n(d[2])} * pi / 180)';

/// A valid Dart double literal. `toString` always keeps a decimal point or
/// exponent, so `1` becomes `1.0` and never an `int` literal.
String _n(double v) => v.toString();

/// A valid, non-empty Dart identifier derived from a part name.
String _sanitize(String name) {
  final buf = StringBuffer();
  for (final ch in name.codeUnits) {
    final ok = (ch >= 0x30 && ch <= 0x39) ||
        (ch >= 0x41 && ch <= 0x5a) ||
        (ch >= 0x61 && ch <= 0x7a) ||
        ch == 0x5f;
    buf.writeCharCode(ok ? ch : 0x5f);
  }
  var s = buf.toString();
  if (s.isEmpty || (s.codeUnitAt(0) >= 0x30 && s.codeUnitAt(0) <= 0x39)) {
    s = 'n$s';
  }
  return s;
}

String _escape(String s) => s.replaceAll('\\', '\\\\').replaceAll('\'', '\\\'');
